
description '快速启动方案'

buildscript {

    ext {

        // Import dependency management from Spring Boot a series of
        springBootVersion = '2.6.14'

        // Test
        junitVersion = '5.8.2'
    }

    repositories {
        mavenCentral()
        mavenLocal()
        gradlePluginPortal()
        maven { url 'https://maven.aliyun.com/repository/central'}
        maven { url 'https://maven.aliyun.com/repository/public'}
        maven { url 'https://maven.aliyun.com/repository/spring'}
    }

    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
    }
}

allprojects {
    apply plugin: 'idea'
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    group 'io.github.DekkerDing'
    version '1.0-SNAPSHOT'
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    compileJava.options.encoding "UTF-8"
    compileTestJava.options.encoding "UTF-8"

    repositories {
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/central'}
        maven { url 'https://maven.aliyun.com/repository/public'}
    }

    dependencies {
        testImplementation "org.junit.jupiter:junit-jupiter-api:${junitVersion}"
        testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:${junitVersion}"
        testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"

    }

    test {
        useJUnitPlatform()
    }
}

subprojects{

    apply plugin: 'org.springframework.boot'

    repositories {
        maven { url 'https://repo1.maven.org/maven2' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/spring' }
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:2021.0.5"
        }
    }

    dependencies {
        annotationProcessor 'org.projectlombok:lombok:1.18.24'
        api 'org.projectlombok:lombok:1.18.24'
        api "org.springframework.boot:spring-boot:${springBootVersion}"
        api "org.springframework.boot:spring-boot-autoconfigure:${springBootVersion}"
        api "org.springframework.boot:spring-boot-configuration-processor:${springBootVersion}"

        // Spring Web
        compileOnly "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"

        // Spring Data JPA
        compileOnly "org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}"

        // Spring Transaction
        compileOnly "org.springframework:spring-tx:5.3.20"

        // Validation
        compileOnly 'javax.validation:validation-api:2.0.1.Final'
    }
}

javadoc {
    afterEvaluate {
        configure(options) {
            encoding "UTF-8"
            charSet 'UTF-8'
            author true
            version true
            failOnError false
            links "http://docs.oracle.com/javase/8/docs/api"
        }
    }
}

//publications {
//
//    mavenJava(MavenPublication) {
//        from components.java
//
//        artifact sourcesJar
//        artifact javadocJar
//
//        pom {
//            name = 'mybatis-plus'
//            packaging 'jar'
//            description = 'An enhanced toolkit of Mybatis to simplify development.'
//            url = 'https://github.com/baomidou/mybatis-plus'
//
//            scm {
//                connection = 'scm:git@github.com:Codearte/gradle-nexus-staging-plugin.git'
//                developerConnection = 'scm:git@github.com:Codearte/gradle-nexus-staging-plugin.git'
//                url = 'https://github.com/baomidou/mybatis-plus'
//            }
//
//            licenses {
//                license {
//                    name = 'The Apache License, Version 2.0'
//                    url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
//                }
//            }
//
//            developers {
//                developer {
//                    id = 'baomidou'
//                    name = 'hubin'
//                    email = 'jobob@qq.com'
//                }
//            }
//
//            withXml {
//                def root = asNode()
//                root.dependencies.'*'.findAll {
//                    def d = it
//                    d.scope.text() == 'runtime' && project.configurations.findByName("implementation").allDependencies.find { dep ->
//                        dep.name == it.artifactId.text()
//                    }.each() {
//                        d.scope*.value = 'compile'
//                        d.appendNode('optional', true)
//                    }
//                }
//            }
//        }
//    }
//}

//jar {
//    enabled = true
//}

bootJar {
    enabled = false
}

idea {
    project {
        jdkName = "1.8"
        languageLevel = "1.8"
        vcs = "Git"
    }
}

configurations.all(){
    Configuration configuration ->
        configuration.resolutionStrategy.failOnVersionConflict()
        configuration.resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            // Force using Maven Central for all dependencies
            // 强制所有依赖使用 Maven Central
        }
}
