pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://maven.aliyun.com/repository/central'}
        maven { url 'https://maven.aliyun.com/repository/public'}
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin'}
    }
}

rootProject.name = 'bootstrap'
include 'e-business-spring-boot-starter'
include 'customer-robot-spring-boot-starter'

